[package]
name = "media"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
api-types = { path = "../api-types" }
app-config = { path = "../app-config" }
jobs = { path = "../jobs" }
orchestrator = { path = "../orchestrator" }
chrono.workspace = true
reqwest.workspace = true
serde_json.workspace = true
storage = { path = "../storage" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
